exporter: file
service_name: JobChainDemo
batch_processor:
  max_queue_size: 1000
  # Reduce the schedule delay to minimize shutdown delay
  schedule_delay_millis: 100
  # Add max export batch size to ensure faster processing
  max_export_batch_size: 512
file_exporter:
  path: temp/trace_output.json
