exporter: console  # Default exporter is console; can be overridden by OTEL_TRACES_EXPORTER env variable.
service_name: MyService  # Can be overridden by OTEL_SERVICE_NAME env variable.
batch_processor:
  max_queue_size: 1000  # Batch processor will handle up to 1000 spans in queue.
  schedule_delay_millis: 1000  # 1-second timeout for exporting spans.
